### ISSUE TITLE
Resend on Rails with ActiveMailer support is not working

### ISSUE THREAD

**Issue by remy727** [resend/resend-ruby#52]
I am going to use the Resend on Rails app with ActionMailer.
I followed [these steps](https://github.com/resend/resend-ruby#rails-and-activemailer-support).
But when I generate a mailer, I get the following error.
```bash
$ bin/rails g mailer shop
<internal:/Users/k3/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require': cannot load such file -- /Users/k3/work/my-app/web/railsend (LoadError)
from <internal:/Users/k3/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
from /Users/k3/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
from /Users/k3/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
from /Users/k3/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/resend-0.1.0/lib/resend.rb:6:in `<main>'
from <internal:/Users/k3/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
from <internal:/Users/k3/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
from /Users/k3/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
from /Users/k3/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
from /Users/k3/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/runtime.rb:60:in `block (2 levels) in require'
from /Users/k3/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/runtime.rb:55:in `each'
from /Users/k3/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/runtime.rb:55:in `block in require'
from /Users/k3/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/runtime.rb:44:in `each'
from /Users/k3/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/runtime.rb:44:in `require'
from /Users/k3/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/bundler.rb:187:in `require'
from /Users/k3/work/my-app/web/config/application.rb:9:in `<main>'
from <internal:/Users/k3/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
from <internal:/Users/k3/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
from /Users/k3/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
from /Users/k3/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.2/lib/rails/command/actions.rb:15:in `require_application!'
from /Users/k3/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.2/lib/rails/command/actions.rb:19:in `boot_application!'
from /Users/k3/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.2/lib/rails/commands/generate/generate_command.rb:21:in `perform'
from /Users/k3/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.3.0/lib/thor/command.rb:28:in `run'
from /Users/k3/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.3.0/lib/thor/invocation.rb:127:in `invoke_command'
from /Users/k3/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.2/lib/rails/command/base.rb:178:in `invoke_command'
from /Users/k3/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.3.0/lib/thor.rb:527:in `dispatch'
from /Users/k3/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.2/lib/rails/command/base.rb:73:in `perform'
from /Users/k3/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.2/lib/rails/command.rb:71:in `block in invoke'
from /Users/k3/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.2/lib/rails/command.rb:149:in `with_argv'
from /Users/k3/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.2/lib/rails/command.rb:69:in `invoke'
from /Users/k3/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.2/lib/rails/commands.rb:18:in `<main>'
from <internal:/Users/k3/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
from <internal:/Users/k3/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
from /Users/k3/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
from bin/rails:4:in `<main>'
```

- Ruby version: `3.2`
- Rails version: `7.1.2`

Any thoughts?

**Comment by drish** [comment]
hey @remy727 thanks for reporting your issue.

looking through your logs, it seems that the resend library installed is version `0.1.0`, could you try the latest version `0.8.0` ? let me know if that fixes your issue.

**Comment by lsglucas** [comment]
@drish I am having the same problem. It appears that we can't install the resend `0.8.0` version because of the **httparty** dependence that is fixed at `0.19.1`.  I use other gems which need **httparty** at least on version `0.21.0`.

**Comment by drish** [comment]
@lsglucas sorry to hear that you ended up having to use another service because of this issue, thanks a lot for reporting it though, that makes a lot of sense. 
I am going to release the `0.8.1` version soon which removes the httparty version pin.

**Comment by drish** [comment]
@remy727 version `0.8.1` has just been released with the unpinning of the httparty gem, please let me know if that fixes your issue.

**Comment by remy727** [comment]
Hello @drish, confirmed version `0.8.1` works. Thank you for quick fix!
